version: "3"

services:

      
  db:
    image: mongo:latest
    container_name: db
    expose:  
      - '27017'  
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - ./server/db/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      back-tier:
        aliases: 
          - mongo
networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
